In [1]:
import load_data
import numpy as np

In [2]:
df = load_data.load_county_level()
print(df)

loading county-level data...
loaded and merged COVID-19 cases/deaths data successfully
     countyFIPS  STATEFP  COUNTYFP   CountyName StateName       State  \
1843      36047     36.0      47.0        Kings        NY    New York   
199       06037      6.0      37.0  Los Angeles        CA  California   
1860      36081     36.0      81.0       Queens        NY    New York   
602       17031     17.0      31.0         Cook        IL    Illinois   
1822      36005     36.0       5.0        Bronx        NY    New York   
...         ...      ...       ...          ...       ...         ...   
1366      27121     27.0     121.0         Pope        MN   Minnesota   
2834      51045     51.0      45.0        Craig        VA    Virginia   
1328      27045     27.0      45.0     Fillmore        MN   Minnesota   
1327      27043     27.0      43.0    Faribault        MN   Minnesota   
3141      15005     15.0       5.0      Kalawao        HI         NaN   

            lat         lon  POP_LAT

In [3]:
print(df.keys())

Index(['countyFIPS', 'STATEFP', 'COUNTYFP', 'CountyName', 'StateName', 'State',
       'lat', 'lon', 'POP_LATITUDE', 'POP_LONGITUDE',
       ...
       '#Deaths_11-16-2020', '#Deaths_11-17-2020', '#Deaths_11-18-2020',
       '#Deaths_11-19-2020', 'deaths', 'cases', 'tot_deaths', 'tot_cases',
       'neighbor_deaths', 'neighbor_cases'],
      dtype='object', length=714)


In [4]:
print(df[['countyFIPS', 'CountyName', '#Deaths_11-11-2020', '#Cases_11-11-2020', 'tot_cases', 'tot_deaths']].head(10))

     countyFIPS   CountyName  #Deaths_11-11-2020  #Cases_11-11-2020  \
1843      36047        Kings                7441              79558   
199       06037  Los Angeles                7216             327964   
1860      36081       Queens                7317              80555   
602       17031         Cook                5717             231462   
1822      36005        Bronx                5014              57657   
98        04013     Maricopa                3747             170207   
3135      12086   Miami-Dade                3693             195991   
1850      36061     New York                3200              38668   
1304      26163        Wayne                3104              48200   
2615      48201       Harris                2877             168746   

      tot_cases  tot_deaths  
1843      83083        7465  
199      353232        7363  
1860      84269        7329  
602      268284        5967  
1822      59856        5023  
98       183177        3850  
3135    

In [5]:
OC_cases = df[(df['StateName']=='CA') & (df['CountyName']=='Orange')]['cases'].values[0]
OC_deaths = df[(df['StateName']=='CA') & (df['CountyName']=='Orange')]['deaths'].values[0]
print(OC_cases, OC_deaths)

[    0     0     0     0     1     1     1     1     1     1     1     1
     1     1     1     1     1     1     1     1     1     1     1     1
     1     1     1     1     1     1     1     1     1     1     1     1
     1     1     1     1     1     1     3     3     3     3     3     5
     5     6     6    13    14    17    22    29    42    53    65    78
    95   125   152   187   256   321   403   431   464   502   606   656
   711   786   834   882   931  1016  1079  1138  1221  1277  1283  1299
  1376  1425  1501  1556  1636  1676  1691  1753  1827  1845  1969  2074
  2126  2151  2252  2393  2537  2636  2743  2819  2873  3004  3092  3240
  3380  3502  3557  3602  3749  3968  4125  4222  4376  4434  4500  4742
  4841  4941  5157  5336  5469  5578  5646  5744  5923  6100  6261  6474
  6574  6678  6783  7064  7321  7440  7527  7614  7737  7987  8153  8269
  8573  8759  8999  9197  9292  9576  9988 10422 10595 10737 11016 11511
 11960 12462 12608 13064 13843 14413 15065 15778 16

In [6]:
# get data first
# convert a time series to a data matrix
def get_data_matrix(data, n):
  # n = 10; the number of past days, the input dimension
  size = len(data)
  m = size-n-1
  #print(n,m,size)
  
  tmp = []
  for i in range(m): # get the latest 100
    tmp.append(data[size-i-n-1:size-i])
  tmp = np.stack(tmp)
  return tmp[:,:-1], tmp[:,-1]#-tmp[:,-2]

In [7]:
X, y = get_data_matrix(OC_cases, 10)
print(X, y)

[[62563 62830 63165 ... 65605 65957 66585]
 [62255 62563 62830 ... 65225 65605 65957]
 [61743 62255 62563 ... 64586 65225 65605]
 ...
 [    0     1     1 ...     1     1     1]
 [    0     0     1 ...     1     1     1]
 [    0     0     0 ...     1     1     1]] [67167 66585 65957 65605 65225 64586 64058 63460 63165 62830 62563 62255
 61743 61421 61112 60841 60604 60298 60115 59882 59718 59442 59213 58980
 58725 58573 58326 58010 57848 57635 57373 57071 56868 56672 56587 56436
 56283 56070 55892 55775 55531 55345 55183 55042 54898 54760 54640 54357
 54118 53909 53751 53557 53448 53315 53069 52904 52622 52538 52382 52201
 52063 51873 51646 51399 51259 51124 50974 50930 50760 50613 50471 50190
 49996 49845 49732 49509 49258 48945 48945 48825 48538 48444 48190 47782
 47459 47090 46642 46307 45954 45801 45308 44936 44507 44212 43925 43709
 43367 42854 42171 41823 41578 40527 39641 39076 38754 38711 38131 38066
 37813 37391 36833 36196 35778 35272 34833 34646 34373 33953 33358 32648
 31743