In [1]:
import load_data
import torch
from Project_Models import RNN_Model
import torch.nn as nn

In [2]:
df = load_data.load_county_level()

loading county-level data...
loaded and merged COVID-19 cases/deaths data successfully


In [3]:
print(df[['CountyName', 'StateName', '#Hospitals', '#ICU_beds', 'cases', 'deaths']].head(2).values)

[['Kings' 'NY' 12.0 318.0
  array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     1,     1,
           3,     3,     4,    10,    14,    24,    24,    34,    53,
          62,   157,   505,  1195,  1518,  2484,  2857,  3494,  4237,
        5232,  6095,  6750,  8129,  8887, 10171, 11160, 12274, 13290,
       15700, 17504, 18558, 19702, 20879, 22082, 23394, 24715, 26243,
       27471, 28404, 29306, 31969, 33521, 34705, 35763, 36482, 37030,
       37694, 38481, 39354, 40648, 41660, 42487, 43014, 43587, 44236,
       44872, 45519, 46275, 46839, 47183, 47579, 47974, 48550, 48998,
       49461, 49817, 50072, 50331, 50667, 51095, 51581, 51991, 52298,
       52485, 52681, 52889, 53385, 53639, 53902, 54175, 54360,

In [4]:
print([i.tolist() for i in df['cases'].head(1).values])

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 3, 3, 4, 10, 14, 24, 24, 34, 53, 62, 157, 505, 1195, 1518, 2484, 2857, 3494, 4237, 5232, 6095, 6750, 8129, 8887, 10171, 11160, 12274, 13290, 15700, 17504, 18558, 19702, 20879, 22082, 23394, 24715, 26243, 27471, 28404, 29306, 31969, 33521, 34705, 35763, 36482, 37030, 37694, 38481, 39354, 40648, 41660, 42487, 43014, 43587, 44236, 44872, 45519, 46275, 46839, 47183, 47579, 47974, 48550, 48998, 49461, 49817, 50072, 50331, 50667, 51095, 51581, 51991, 52298, 52485, 52681, 52889, 53385, 53639, 53902, 54175, 54360, 54560, 54779, 55147, 55446, 55727, 55900, 56053, 56242, 56405, 56587, 56770, 56966, 57131, 57260, 57367, 57484, 57605, 57733, 57919, 58059, 58177, 58274, 58386, 58502, 58634, 58761, 58874, 58949, 59047, 59111, 59206, 59311, 59420, 59507, 59576, 59650, 59742, 59855, 59957, 60078, 60149, 60211, 60281, 60281, 60461, 60560, 60647, 60748, 60815, 60904, 6

In [5]:
result = []
for cityInfo in df[['countyFIPS'] + ['#Hospitals', '#ICU_beds']].head(10).values:
    allCityInfo = []  # form the sequence
    for dayICases, dayIDeath in zip(df[(df['countyFIPS']==cityInfo[0])]['cases'].values[0], df[(df['countyFIPS']==cityInfo[0])]['deaths'].values[0]):
        oneCityOneDay = cityInfo[1:].tolist()
        oneCityOneDay.append(dayICases)
        oneCityOneDay.append(dayIDeath)
        allCityInfo.append(oneCityOneDay)
    result.append(allCityInfo)

In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
result = torch.tensor(result, dtype=torch.float32).to(device)

d:\johnathan\python\lib\site-packages\ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [7]:
result

tensor([[[1.2000e+01, 3.1800e+02, 0.0000e+00, 0.0000e+00],
         [1.2000e+01, 3.1800e+02, 0.0000e+00, 0.0000e+00],
         [1.2000e+01, 3.1800e+02, 0.0000e+00, 0.0000e+00],
         ...,
         [1.2000e+01, 3.1800e+02, 8.2090e+04, 7.4550e+03],
         [1.2000e+01, 3.1800e+02, 8.2543e+04, 7.4570e+03],
         [1.2000e+01, 3.1800e+02, 8.3083e+04, 7.4650e+03]],

        [[7.6000e+01, 2.1260e+03, 0.0000e+00, 0.0000e+00],
         [7.6000e+01, 2.1260e+03, 0.0000e+00, 0.0000e+00],
         [7.6000e+01, 2.1260e+03, 0.0000e+00, 0.0000e+00],
         ...,
         [7.6000e+01, 2.1260e+03, 3.4452e+05, 7.2990e+03],
         [7.6000e+01, 2.1260e+03, 3.4834e+05, 7.3350e+03],
         [7.6000e+01, 2.1260e+03, 3.5323e+05, 7.3630e+03]],

        [[6.0000e+00, 1.2900e+02, 0.0000e+00, 0.0000e+00],
         [6.0000e+00, 1.2900e+02, 0.0000e+00, 0.0000e+00],
         [6.0000e+00, 1.2900e+02, 0.0000e+00, 0.0000e+00],
         ...,
         [6.0000e+00, 1.2900e+02, 8.3311e+04, 7.3230e+03],
         [

In [12]:
model = RNN_Model.RNN(4, 128, 2).to(device)

In [15]:
criterion = nn.MSELoss()
learning_rate = 0.005
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [13]:
print(model(result))

tensor([[ 0.1474, -0.3594],
        [-0.0266, -0.2634],
        [ 0.1474, -0.3594],
        [-0.0266, -0.2634],
        [ 0.1474, -0.3594],
        [-0.1313, -0.2907],
        [-0.1434, -0.3448],
        [ 0.0902, -0.2336],
        [-0.0266, -0.2634],
        [-0.1434, -0.3448]], device='cuda:0', grad_fn=<AddmmBackward>)


In [24]:
print(df['tot_cases'].values)


[ 83083 353232  84269 ...    536    430      0]


In [31]:
y = []
for totalCases, totalDeaths in zip(df['tot_cases'].head(10).values, df['tot_deaths'].head(10).values):
    y.append([totalCases, totalDeaths])
y = torch.tensor(y, dtype=torch.float32).to(device)
print(y)

tensor([[ 83083.,   7465.],
        [353232.,   7363.],
        [ 84269.,   7329.],
        [268284.,   5967.],
        [ 59856.,   5023.],
        [183177.,   3850.],
        [209166.,   3738.],
        [ 41263.,   3217.],
        [ 54721.,   3145.],
        [177466.,   2943.]], device='cuda:0')


In [32]:
print(criterion(model(result), y))

tensor(1.6406e+10, device='cuda:0', grad_fn=<MseLossBackward>)


In [33]:
for epoch in range(10):
    outputs = model(result)
    loss = criterion(outputs, y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    

In [34]:
print(model(result))

tensor([[151438.4062,   5003.5649],
        [151438.4062,   5003.5649],
        [151438.4062,   5003.5649],
        [151438.4062,   5003.5649],
        [151438.4062,   5003.5649],
        [151438.4062,   5003.5649],
        [151438.4062,   5003.5649],
        [151438.4062,   5003.5649],
        [151438.4062,   5003.5649],
        [151438.4062,   5003.5649]], device='cuda:0', grad_fn=<AddmmBackward>)
